import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-hotel-ota-commission-revenue-recovery",
  "engine": "recovery",
  "title": "Hotel OTA Commission & Revenue Recovery",
  "shortTitle": "Hotel Distribution Recovery",
  "tagline": "Recover commission, cancellation, no-show, rate, and settlement leakage by stay",
  "industry": "Hospitality Distribution Finance",
  "uiPort": 4563,
  "apiPort": 5563,
  "accent": "#b91c1c",
  "currency": "USD",
  "primaryOutcome": "Hotel net revenue protected across every OTA reservation and settlement",
  "valueNarrative": "Reconcile PMS reservations, channel-manager messages, stay outcomes, rates, taxes, cancellations, commissions, and OTA settlements.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "OTA charged commission",
    "expectedLabel": "Contract-supported commission",
    "varianceLabel": "Potential distribution recovery",
    "direction": "actual-minus-expected",
    "finding": "Reservation, stay, tax, cancellation, and OTA contract evidence indicate excessive distribution charges or missing net revenue.",
    "actions": [
      "Match OTA reservations to PMS stays and settlements",
      "Apply commission rules to eligible room revenue",
      "Exclude taxes, cancellations, no-shows, and disputed stays",
      "Submit adjustment and reconcile OTA settlement"
    ]
  }
},[
feature("ota-contract-and-rate-library","HDR01","OTA contract and rate library","Reconcile ota contract and rate library using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed ota contract and rate library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]}),
feature("property-and-channel-registry","HDR02","Property and channel registry","Reconcile property and channel registry using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed property and channel registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]}),
feature("reservation-ingestion","HDR03","Reservation ingestion","Reconcile reservation ingestion using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed reservation ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]}),
feature("pms-stay-matching","HDR04","PMS stay matching","Reconcile pms stay matching using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed pms stay matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]}),
feature("room-rate-parity-validation","HDR05","Room-rate parity validation","Reconcile room-rate parity validation using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed room-rate parity validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]}),
feature("commission-base-recalculation","HDR06","Commission base recalculation","Reconcile commission base recalculation using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed commission base recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]}),
feature("tax-and-fee-exclusion-control","HDR07","Tax and fee exclusion control","Reconcile tax and fee exclusion control using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed tax and fee exclusion control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]}),
feature("cancellation-and-no-show-audit","HDR08","Cancellation and no-show audit","Reconcile cancellation and no-show audit using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed cancellation and no-show audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]}),
feature("duplicate-commission-detection","HDR09","Duplicate commission detection","Reconcile duplicate commission detection using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed duplicate commission detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]}),
feature("virtual-card-reconciliation","HDR10","Virtual card reconciliation","Reconcile virtual card reconciliation using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed virtual card reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]}),
feature("merchant-settlement-reconciliation","HDR11","Merchant settlement reconciliation","Reconcile merchant settlement reconciliation using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed merchant settlement reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]}),
feature("chargeback-and-refund-control","HDR12","Chargeback and refund control","Reconcile chargeback and refund control using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed chargeback and refund control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]}),
feature("ota-dispute-package","HDR13","OTA dispute package","Reconcile ota dispute package using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed ota dispute package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]}),
feature("settlement-recovery-tracking","HDR14","Settlement recovery tracking","Reconcile settlement recovery tracking using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed settlement recovery tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]}),
feature("channel-profitability-analytics","HDR15","Channel profitability analytics","Reconcile channel profitability analytics using OTA agreements, PMS reservations, channel messages, folios, stay status, taxes, commission invoices, and settlements.","Produce a governed channel profitability analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["ota","Online Travel Agency","text","GlobalStay"],["propertyPeriod","Property / Period","text","Harbor Hotel / 2026-06"],["chargedAmount","OTA Commission Charged","currency",386000],["supportedAmount","Contract-Supported Commission","currency",329500]],{amountField:"chargedAmount",subjects:["Urban full-service hotel","Airport select-service hotel","Resort property","Extended-stay property","Multi-property management group"]})
]);
